### PR TITLE
fix: change server proxy preset for @nuxt/icon

### LINKED ISSUE #780: @nuxt/icon does not work
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      devtools, modules, app, i18n, icon, imports, runtimeConfig, vue, compatibilityDate, vite
- Runtime Modules:  @nuxtjs/storybook@8.3.0-28771560.b2b9b16, @nuxt/image@1.8.0, @pinia/nuxt@0.5.3, @nuxt/icon@1.5.1, @nuxtjs/i18n@8.5.3
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/exophunk/nuxt-storybook-showcase

### Describe the bug

Using the official [Nuxt Icon module](https://nuxt.com/modules/icon) does not work with storybook. Icons do not show in storybook stories. As far as I tested, both remote Icons from iconify, but also local icons do not work.

is there anyway to configure nuxt + storybook + icons to work? Storybook for visual components is pretty pointless if they don't show correctly.

Reproduction Repo: https://github.com/exophunk/nuxt-storybook-showcase
Stackblitz: https://stackblitz.com/~/github.com/exophunk/nuxt-storybook-showcase
although on stackblitz, i'm never able to get this things run properly
See the [NuxtIcon](https://github.com/exophunk/nuxt-storybook-showcase/blob/main/components/NuxtIcon.stories.ts) story.

```
<Icon name="uil:github" style="color: black" />
```

Problem: No output at all (empty template)

### Additional context

The reproduction uses a baseURL to showcase another issue but Icons should not be touched by that. Open the app at localhost:3000/my-base or remove baseurl for this example. but should not matter.

### PR DESCRIPTION
**Pull request by sawden**
### 🔗 Linked issue
Resolves #780 

### 📚 Description

Reproduced #780 using latest `@nuxtjs/storybook v8.3.3` and can confirm that icons couldn’t be loaded in Storybook because the `api/_nuxt_icon` endpoint (from @nuxt/icon) isn’t accessible on port 6006.

So I checked all currently proxied routes and noticed that there is a `_icon` route, but it isn’t used by `@nuxt/icon` or any other [official Nuxt module](https://github.com/nuxt), [community module](https://github.com/nuxt-modules), or icon module listed [here](https://nuxt.com/modules?q=icon). There’s also no Git history explaining why `_icon` was added. Therefore, I replaced it with the actual `api/_nuxt_icon` endpoint from `@nuxt/icon`

| Route             | Module                | Code Reference |
|-------------------|-----------------------|-----------|
| `_nuxt`             | core (buildassetsdir) | [Docs](https://nuxt.com/docs/api/nuxt-config#buildassetsdir)      |
| `_ipx`              | @nuxt/image           | [GitHub](https://github.com/nuxt/image/blob/782c8f542deb12b669c9d4365638dae059d7df55/src/ipx.ts#L20)    |
| `__nuxt_devtools__` | @nuxt/devtools-kit    | [GitHub](https://github.com/nuxt/devtools/blob/04269d03b5ce89388528b42f3de8a40a3ddc8bf5/packages/devtools/client/nuxt.config.ts#L69)    |
| `__nuxt_island`     | core (\<NuxtIsland\>)  | [GitHub](https://github.com/nuxt/nuxt/blob/61ddea167bbe9351062b4a1514f02dce84990d0d/packages/nuxt/src/app/plugins/revive-payload.client.ts#L24)    |
| `api/_nuxt_icon`    | @nuxt/icon            | [GitHub](https://github.com/nuxt/icon/blob/0356c34fd57f5aba95e70f2d51362bacb75f40c4/src/module.ts#L83)    |
| `_icon`             | ?                     | ?         |

This change fixes icon loading with @nuxt/icon in Storybook.

**Before:**
| default | [includeCustomCollections](https://nuxt.com/modules/icon#client-bundle) enabled |
|-------------------|-----------------------|
| before-sb | before-sb-client-bundle |

**After:**
| default | [includeCustomCollections](https://nuxt.com/modules/icon#client-bundle) enabled |
|-------------------|-----------------------|
| after-sb | after-sb|

### CODE REVIEW

**Review by tobiasdiez — APPROVED** [review]

**Comment by tobiasdiez** [comment]
Doesn't have to be part of this PR, but could you please add an example for the `@nuxt/icon` module in `examples/showcase` so that we make sure to not break it again in the future.

File: packages/storybook-addon/src/preset.ts [hunk 1]
```diff
@@ -365,7 +365,7 @@ async function getPackageDir(packageName: string) {
 
 export function getNuxtProxyConfig(nuxt: Nuxt) {
   const port = nuxt.options.runtimeConfig.app.port ?? 3000
-  const route = '^/(_nuxt|_ipx|_icon|__nuxt_devtools__|__nuxt_island)'
+  const route = '^/(_nuxt|_ipx|api/_nuxt_icon|__nuxt_devtools__|__nuxt_island)'
```
Comment (chakAs3) [inline packages/storybook-addon/src/preset.ts:368]: can you keep _icon as well to avoid  breaking for older module versions
